version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.3
  api:
    build: ./api
    command: make run-dev
    volumes:
      - ./api:/app
    depends_on:
      - elasticsearch
  importer:
    build: ./importer
    volumes:
      - ./importer:/app
    depends_on:
      - elasticsearch
  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    depends_on:
      - api
